# Generated by Django 4.2.3 on 2023-10-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_name_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('search_requests', models.CharField(blank=True, max_length=255, null=True)),
                ('search_requests_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('description_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, default='r', max_length=10, null=True)),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(blank=True, default='UAH', max_length=3, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, default='шт.', max_length=10, null=True)),
                ('image_link', models.URLField(blank=True, max_length=255, null=True)),
                ('availability', models.CharField(blank=True, default='+', max_length=10, null=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('packing_method', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('h1', models.CharField(blank=True, max_length=255, null=True)),
                ('h1_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('html_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('html_group_name_uk', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
