# Generated by Django 4.2.3 on 2023-10-11 08:03

from django.db import migrations, models
import django.db.models.deletion
import django_celery_beat.validators
import django_lifecycle.mixins
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsePeriodicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('time', models.TimeField()),
                ('day_of_week', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('0', 'Sunday'), ('*', 'All')], default='*', max_length=24, validators=[django_celery_beat.validators.day_of_week_validator], verbose_name='Day(s) Of The Week')),
                ('month_of_year', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December'), ('*', 'All')], default='*', max_length=64, validators=[django_celery_beat.validators.month_of_year_validator], verbose_name='Month(s) Of The Year')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (10, 'Processing'), (20, 'Finished'), (30, 'Failed')], default=0)),
                ('periodic_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parser.parseperiodictask')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='parser.task'),
        ),
    ]
