# Generated by Django 4.2.3 on 2023-10-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_product_product_identificator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='h1',
            new_name='html_header',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='h1_uk',
            new_name='html_header_uk',
        ),
    ]
