# Generated by Django 4.2.3 on 2023-10-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_rename_h1_product_html_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packing_method_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
