# Generated by Django 4.2.3 on 2023-10-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='html_group_name',
            new_name='html_keywords',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='html_group_name_uk',
            new_name='html_keywords_uk',
        ),
    ]
