# Generated by Django 4.2.3 on 2023-10-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0009_product_height_product_length_product_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
