# Generated by Django 4.2.3 on 2023-10-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0011_alter_product_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='html_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='html_header_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_uk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
