# Generated by Django 4.2.3 on 2023-10-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0012_alter_product_html_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
